# Copyright (C) 2023 Daniel Mueller <deso@posteo.net>
# SPDX-License-Identifier: CC0-1.0

blank_lines_upper_bound = 2
edition = "2024"
imports_granularity = "item"
imports_layout = "Vertical"
match_block_trailing_comma = true
tab_spaces = 2
trailing_semicolon = false
